export const ABS_CIRCUIT = [
  { id: "abs_gainage", label: "Gainage face + chaque côté", emoji: "🧱", reps: "1min + 30s/côté", image: "abdos-gainage.jpg" },
  { id: "abs_oblique", label: "Oblique de chaque côté", emoji: "🔄", reps: "20 rep/côté", image: "abdos-oblique.jpg" },
  { id: "abs_releve_jambes", label: "Relevé de jambes à la barre", emoji: "🦵", reps: "Max rep", image: "abdos-releve-jambes-barre.jpg" },
  { id: "abs_roulette", label: "Roulette", emoji: "🛞", reps: "Max rep", image: "abdos-roulette.jpg" },
  { id: "abs_crunch", label: "Crunch jambes/bras tendues", emoji: "💪", reps: "10-20 rep", image: "abdos-crunch-jambes-bras-tendues.jpg" },
];

export const WARMUP_HDC = [
  { id: "w_coiffe", label: "Coiffe des rotateurs", emoji: "🔄", reps: "20 rep de chaque", image: "echauff-hdc-coiffe-rotateurs.jpg" },
  { id: "w_mobilite_epaule", label: "Mobilité épaule élastique", emoji: "🔴", reps: "10 rep", image: "echauff-hdc-mobilite-epaule.jpg" },
  { id: "w_rotation_epaule", label: "Rotation circulaire épaule", emoji: "🔁", reps: "20 de chaque (avant/arrière)", image: "echauff-hdc-rotation-circulaire-epaule.jpg" },
  { id: "w_pompes_surel", label: "Pompes mains surélevées", emoji: "🫸", reps: "10-20 rep", image: "echauff-hdc-pompes-mains-surelevees.jpg" },
  { id: "w_aust_pronation", label: "Tractions australiennes pronation", emoji: "🇦🇺", reps: "10-20 rep", image: "echauff-hdc-tractions-australiennes-pronation.jpg" },
];

export const WARMUP_BDC = [
  { id: "w_circulaire_bassin", label: "Mouvement circulaire bassin", emoji: "🔄", reps: "10 dans chaque sens", image: "echauff-bdc-mouvement-circulaire-bassin.jpg" },
  { id: "w_jambe_barriere", label: "Mouvement jambe contre barrière", emoji: "🦵", reps: "10 de chaque", image: "echauff-bdc-mouvement-jambe-barriere.jpg" },
  { id: "w_balancement", label: "Balancement de jambe", emoji: "🦿", reps: "10 de chaque", image: "echauff-bdc-balancement-jambe.jpg" },
  { id: "w_squat_iso", label: "Squat isométrique", emoji: "🧱", reps: "30 sec", image: "echauff-bdc-squat-isometrique.jpg" },
];

export const SPORT_DAYS = {
  1: {
    id: "push", type: "muscu", label: "PUSH", subtitle: "Pec, Épaules, Triceps", emoji: "🏋️", hasAbsCircuit: true, warmup: "hdc",
    exercises: [
      { id: "push_t1a", label: "Muscle Up", emoji: "🔝", series: 5, reps: "5-10", rest: 90, superset: "push_t1b", image: "push-muscle-up.jpg" },
      { id: "push_t1b", label: "Dips Barre Parallèle", emoji: "⬇️", series: 5, reps: "10-20", rest: 90, superset: "push_t1c", image: "push-dips-barre-parallele.jpg" },
      { id: "push_t1c", label: "Pompes Classique", emoji: "🫸", series: 5, reps: "10-20", rest: 90, image: "push-pompes-classique.jpg" },
      { id: "push_t2a", label: "Dips Barre + Blocage Iso 90°", emoji: "⏸️", series: 5, reps: "15-20 + 15-20s", rest: 90, superset: "push_t2b", image: "push-dips-barre-blocage-isometrique.jpg" },
      { id: "push_t2b", label: "Élévation Frontale Élastique", emoji: "🔴", series: 5, reps: "15-20", rest: 90, image: "push-elevation-frontale-elastique.jpg" },
      { id: "push_t3a", label: "Dips Épaules Blocage 90° + Explosif", emoji: "💥", series: 5, reps: "15s + 15-20", rest: 90, superset: "push_t3b", image: "push-dips-epaules-blocage-explosif.jpg" },
      { id: "push_t3b", label: "Pompes Pieds Surélevées", emoji: "⬆️", series: 5, reps: "15-20", rest: 90, image: "push-pompes-pieds-surelevees.jpg" },
      { id: "push_t4a", label: "Barre au Front", emoji: "💪", series: 5, reps: "12", rest: 90, superset: "push_t4b", image: "push-barre-au-front.jpg" },
      { id: "push_t4b", label: "Dips sur Banc", emoji: "🪑", series: 5, reps: "15", rest: 90, superset: "push_t4c", image: "push-dips-sur-banc.jpg" },
      { id: "push_t4c", label: "Extension Triceps Élastique", emoji: "🔴", series: 5, reps: "15-20", rest: 90, image: "push-extension-triceps-elastique.jpg" },
    ],
  },
  2: {
    id: "nat_hiit", type: "natation", label: "NATATION HIIT", subtitle: "Sprints & intensité", emoji: "🏊",
    blocks: [
      { id: "warmup_brasse", label: "Échauffement — 100m brasse tranquille", distance: 100, emoji: "🐢" },
      { id: "warmup_crawl", label: "Échauffement — 100m crawl tranquille", distance: 100, emoji: "🐢" },
      { id: "b1_1", label: "50m crawl sprint (85-90%) — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_2", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_3", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_4", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_5", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_6", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_7", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_8", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_9", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b1_10", label: "50m crawl sprint — 30s récup", distance: 50, emoji: "⚡" },
      { id: "b2_1", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_2", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_3", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_4", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_5", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_6", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_7", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b2_8", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "b3_1", label: "50m crawl sprint MAX (95%) — 40s récup", distance: 50, emoji: "🔥" },
      { id: "b3_2", label: "50m crawl sprint MAX — 40s récup", distance: 50, emoji: "🔥" },
      { id: "b3_3", label: "50m crawl sprint MAX — 40s récup", distance: 50, emoji: "🔥" },
      { id: "b3_4", label: "50m crawl sprint MAX — 40s récup", distance: 50, emoji: "🔥" },
      { id: "b3_5", label: "50m crawl sprint MAX — 40s récup", distance: 50, emoji: "🔥" },
      { id: "b3_6", label: "50m crawl sprint MAX — 40s récup", distance: 50, emoji: "🔥" },
      { id: "b4_1", label: "25m papillon (ou crawl sprint) — 30s récup", distance: 25, emoji: "🦋" },
      { id: "b4_2", label: "25m papillon — 30s récup", distance: 25, emoji: "🦋" },
      { id: "b4_3", label: "25m papillon — 30s récup", distance: 25, emoji: "🦋" },
      { id: "b4_4", label: "25m papillon — 30s récup", distance: 25, emoji: "🦋" },
      { id: "cooldown", label: "Retour au calme — 200m brasse souple", distance: 200, emoji: "🐢" },
    ],
    totalDistance: 1600,
    info: "55 min — ~500-600 kcal — Crawl, brasse, papillon",
  },
  3: {
    id: "pull", type: "muscu", label: "PULL", subtitle: "Dos, Biceps", emoji: "🏋️", hasAbsCircuit: true, warmup: "hdc",
    exercises: [
      { id: "pull_s1a", label: "Traction Prise Pronation", emoji: "💪", series: 5, reps: "15", rest: 120, superset: "pull_s1b", image: "pull-traction-pronation.jpg" },
      { id: "pull_s1b", label: "Tirage Élastique Bûcheron", emoji: "🪓", series: 5, reps: "15/côté", rest: 120, image: "pull-tirage-elastique-bucheron.jpg" },
      { id: "pull_s2a", label: "Traction Supination Prise Serrée", emoji: "✊", series: 5, reps: "15", rest: 90, superset: "pull_s2b", image: "pull-traction-supination-prise-serree.jpg" },
      { id: "pull_s2b", label: "Curl Biceps Barre Dips", emoji: "💪", series: 5, reps: "blocage 5s + max rep", rest: 90, image: "pull-curl-biceps-barre-dips.jpg" },
      { id: "pull_s3a", label: "Traction Neutre Échelle Large", emoji: "↔️", series: 5, reps: "15", rest: 90, superset: "pull_s3b", image: "pull-traction-neutre-echelle-large.jpg" },
      { id: "pull_s3b", label: "Traction Australienne Barre Parallèle", emoji: "🇦🇺", series: 5, reps: "15", rest: 90, image: "pull-traction-australienne-barre-parallele.jpg" },
      { id: "pull_ex4", label: "Traction Pronation Serrée Tempo Dégressif", emoji: "⏱️", series: 5, reps: "descente 5-10s", rest: 90, image: "pull-traction-pronation-serree-tempo.jpg" },
    ],
  },
  4: {
    id: "nat_volume", type: "natation", label: "NATATION Volume", subtitle: "Endurance & distance", emoji: "🏊",
    blocks: [
      { id: "warmup", label: "Échauffement — 200m brasse tranquille", distance: 200, emoji: "🐢" },
      { id: "v1_1", label: "50m crawl allure modérée — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_2", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_3", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_4", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_5", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_6", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_7", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v1_8", label: "50m crawl modéré — 15s récup", distance: 50, emoji: "🌊" },
      { id: "v2_1", label: "50m brasse allure modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_2", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_3", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_4", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_5", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_6", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_7", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v2_8", label: "50m brasse modérée — 15s récup", distance: 50, emoji: "🐸" },
      { id: "v3_1", label: "50m alternée crawl/brasse — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_2", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_3", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_4", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_5", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_6", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_7", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "v3_8", label: "50m alternée — 15s récup", distance: 50, emoji: "🔄" },
      { id: "cooldown", label: "Retour au calme — 200m brasse souple", distance: 200, emoji: "🐢" },
    ],
    totalDistance: 1600,
    info: "55 min — ~450-550 kcal — Crawl & brasse allure modérée",
  },
  5: {
    id: "fullhdc", type: "muscu", label: "FULL HDC", subtitle: "Full Haut du Corps", emoji: "🏋️", hasAbsCircuit: true, warmup: "hdc",
    exercises: [
      { id: "fhdc_s1a", label: "Dips en Haut de la Barre", emoji: "⬆️", series: 5, reps: "20", rest: 120, superset: "fhdc_s1b", image: "push-dips-barre-parallele.jpg" },
      { id: "fhdc_s1b", label: "Traction Pronation (sans lâcher)", emoji: "💪", series: 5, reps: "15", rest: 120, image: "pull-traction-pronation.jpg" },
      { id: "fhdc_s2a", label: "Dips Barre Parallèle", emoji: "⬇️", series: 5, reps: "20", rest: 90, superset: "fhdc_s2b", image: "push-dips-barre-parallele.jpg" },
      { id: "fhdc_s2b", label: "Traction Australienne Prise Neutre", emoji: "🇦🇺", series: 5, reps: "20", rest: 90, image: "pull-traction-australienne-barre-parallele.jpg" },
      { id: "fhdc_s3a", label: "Traction Australienne Pronation", emoji: "🔄", series: 5, reps: "30", rest: 90, superset: "fhdc_s3b", image: "fullhdc-traction-australienne-pronation.jpg" },
      { id: "fhdc_s3b", label: "Pompes", emoji: "🫸", series: 5, reps: "30", rest: 90, image: "push-pompes-classique.jpg" },
      { id: "fhdc_s4a", label: "Barre au Front", emoji: "💪", series: 5, reps: "15", rest: 90, superset: "fhdc_s4b", image: "push-barre-au-front.jpg" },
      { id: "fhdc_s4b", label: "Curl Biceps Barre Dips", emoji: "✊", series: 5, reps: "15", rest: 90, image: "pull-curl-biceps-barre-dips.jpg" },
    ],
  },
  6: {
    id: "legs", type: "muscu", label: "LEGS", subtitle: "Full Bas du Corps", emoji: "🦵", warmup: "bdc",
    exercises: [
      { id: "legs_s1a", label: "Squat Talon Surélevé + Isométrie", emoji: "🦵", series: 5, reps: "20 + 20s blocage", rest: 90, superset: "legs_s1b", image: "legs-squat-talon-sureleve-isometrie.jpg" },
      { id: "legs_s1b", label: "Marche des Canards", emoji: "🦆", series: 5, reps: "30 mètres", rest: 90, image: "legs-marche-canards.jpg" },
      { id: "legs_s2a", label: "Squat Bulgare", emoji: "🦵", series: 5, reps: "20/jambe", rest: 90, superset: "legs_s2b", image: "legs-squat-bulgare.jpg" },
      { id: "legs_s2b", label: "Ischio Unilatéral sur Chaise", emoji: "🪑", series: 5, reps: "20/jambe", rest: 90, image: "legs-ischio-unilateral-chaise.jpg" },
      { id: "legs_t3a", label: "Squat + Box Jump + Squat Sauté", emoji: "📦", series: 5, reps: "15 + 15 + 15", rest: 90, image: "legs-squat-box-jump-squat-saute.jpg" },
      { id: "legs_s4a", label: "Fentes Sautées Alternées", emoji: "🦘", series: 5, reps: "8/jambe", rest: 90, superset: "legs_s4b", image: "legs-fentes-sautees-alternees.jpg" },
      { id: "legs_s4b", label: "Saut en Longueur Pied Joint", emoji: "🏃", series: 5, reps: "10 sauts", rest: 90, image: "legs-saut-longueur-pied-joint.jpg" },
    ],
  },
  0: {
    id: "nat_pyramide", type: "natation", label: "NATATION Pyramide", subtitle: "Montée/descente", emoji: "🏊",
    blocks: [
      { id: "warmup", label: "Échauffement — 200m (brasse + crawl)", distance: 200, emoji: "🐢" },
      { id: "pyr_s1_25a", label: "25m crawl sprint — 15s récup", distance: 25, emoji: "📈" },
      { id: "pyr_s1_50a", label: "50m crawl sprint — 20s récup", distance: 50, emoji: "📈" },
      { id: "pyr_s1_50b", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "pyr_s1_50c", label: "50m crawl sprint — 20s récup", distance: 50, emoji: "📉" },
      { id: "pyr_s1_25b", label: "25m crawl sprint", distance: 25, emoji: "📉" },
      { id: "pyr_s2_25a", label: "25m crawl sprint — 15s récup", distance: 25, emoji: "📈" },
      { id: "pyr_s2_50a", label: "50m crawl sprint — 20s récup", distance: 50, emoji: "📈" },
      { id: "pyr_s2_50b", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "pyr_s2_50c", label: "50m crawl sprint — 20s récup", distance: 50, emoji: "📉" },
      { id: "pyr_s2_25b", label: "25m crawl sprint", distance: 25, emoji: "📉" },
      { id: "pyr_s3_25a", label: "25m crawl sprint — 15s récup", distance: 25, emoji: "📈" },
      { id: "pyr_s3_50a", label: "50m crawl sprint — 20s récup", distance: 50, emoji: "📈" },
      { id: "pyr_s3_50b", label: "50m brasse rapide — 20s récup", distance: 50, emoji: "🐸" },
      { id: "pyr_s3_50c", label: "50m crawl sprint — 20s récup", distance: 50, emoji: "📉" },
      { id: "pyr_s3_25b", label: "25m crawl sprint", distance: 25, emoji: "📉" },
      { id: "fin_1", label: "25m sprint MAX crawl — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_2", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_3", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_4", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_5", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_6", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_7", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "fin_8", label: "25m sprint MAX — 20s récup", distance: 25, emoji: "🔥" },
      { id: "cooldown", label: "Retour au calme — 200m brasse souple", distance: 200, emoji: "🐢" },
    ],
    totalDistance: 1400,
    info: "55 min — ~450-550 kcal — Pyramide ×3 + finisher 8×25m",
  },
};

export const REST_PRESETS = [
  { label: "2:00", seconds: 120 },
  { label: "1:30", seconds: 90 },
  { label: "1:00", seconds: 60 },
];
